export type LandingTool = { path: string; toolSlug: string; title: string; h1: string; description: string; summary: string; steps: string[]; localBenefit: string; related: string[]; acceptsImages?: boolean; multi?: boolean; faq: Array<{ question: string; answer: string }> };

const commonFaq = (verb: string) => [{ question: `Does CachePDF ${verb} my document locally?`, answer: "Supported PDF processing happens in the browser. CachePDF does not require sending selected document contents to CachePDF for processing." }, { question: "Does this change my original file?", answer: "No. CachePDF generates a new output while leaving the selected source file unchanged." }];

export const landingTools: LandingTool[] = [
  { path: "/merge-pdf", toolSlug: "merge-pdf", title: "Merge PDF Privately in Your Browser | CachePDF", h1: "Merge PDFs locally", description: "Combine PDFs directly in your browser with CachePDF. No account is required for supported local processing.", summary: "Combine multiple PDF files into one fresh document without moving the selected document contents into a CachePDF processing service.", steps: ["Open the PDFs you want to combine.", "Set the document order.", "Merge the files locally.", "Export the new PDF."], localBenefit: "A merger is often used for sensitive work packets. CachePDF keeps the supported merge operation in the browser and creates a separate output.", related: ["/split-pdf", "/reorder-pdf-pages", "/extract-pdf-pages"], multi: true, faq: commonFaq("merge") },
  { path: "/split-pdf", toolSlug: "split-pdf", title: "Split PDF Locally — No File Upload | CachePDF", h1: "Split PDF pages locally", description: "Split selected PDF pages into individual PDFs in your browser with CachePDF.", summary: "Select the pages you need and create a ZIP of separate, one-page PDF files from the local document.", steps: ["Open a PDF.", "Select the thumbnails to separate.", "Create individual PDFs locally.", "Export the ZIP archive."], localBenefit: "The split workflow is useful when only a few pages should travel onward. Your source document remains unchanged.", related: ["/merge-pdf", "/reorder-pdf-pages", "/delete-pdf-pages"], faq: commonFaq("split") },
  { path: "/reorder-pdf-pages", toolSlug: "reorder-pages", title: "Reorder PDF Pages in Your Browser | CachePDF", h1: "Reorder PDF pages locally", description: "Arrange PDF page thumbnails in your browser and export a newly ordered PDF.", summary: "Review visible page thumbnails, move them into the required sequence, and export a new ordered document.", steps: ["Open a PDF.", "Inspect page thumbnails.", "Drag pages into a new sequence.", "Export the reordered PDF."], localBenefit: "Page ordering stays visible and local, which is useful for reviewing document structure before a fresh export.", related: ["/merge-pdf", "/rotate-pdf", "/extract-pdf-pages"], faq: commonFaq("reorder") },
  { path: "/rotate-pdf", toolSlug: "rotate-pages", title: "Rotate PDF Pages Locally | CachePDF", h1: "Rotate PDF pages locally", description: "Rotate selected PDF pages directly in your browser and export a new PDF.", summary: "Correct sideways scans or individual pages without overwriting the source document.", steps: ["Open a PDF.", "Select pages or rotate thumbnails.", "Choose the rotation.", "Export the corrected PDF."], localBenefit: "The supported rotation action runs in the browser and keeps the original file intact.", related: ["/reorder-pdf-pages", "/split-pdf", "/pdf-to-png"], faq: commonFaq("rotate") },
  { path: "/extract-pdf-pages", toolSlug: "extract-pages", title: "Extract PDF Pages Locally | CachePDF", h1: "Extract PDF pages locally", description: "Create a new PDF from selected pages in your browser with CachePDF.", summary: "Keep the relevant pages and export a focused new PDF without changing the source file.", steps: ["Open a PDF.", "Select the pages to keep.", "Create a new local PDF.", "Export the result."], localBenefit: "Extraction makes it easier to share only the necessary pages while preserving the original file locally.", related: ["/delete-pdf-pages", "/split-pdf", "/merge-pdf"], faq: commonFaq("extract") },
  { path: "/delete-pdf-pages", toolSlug: "delete-pages", title: "Delete PDF Pages Locally | CachePDF", h1: "Delete PDF pages locally", description: "Remove selected pages from a new PDF in your browser with CachePDF.", summary: "Choose pages to remove, review the local action, and export a new document while the original stays unchanged.", steps: ["Open a PDF.", "Select pages to remove.", "Run the local action.", "Export the new PDF."], localBenefit: "CachePDF creates a new document copy, rather than destructively modifying the source file.", related: ["/extract-pdf-pages", "/split-pdf", "/remove-pdf-metadata"], faq: commonFaq("delete pages from") },
  { path: "/jpg-to-pdf", toolSlug: "images-to-pdf", title: "JPG to PDF in Your Browser | CachePDF", h1: "Convert JPG images to PDF locally", description: "Create a PDF from JPG images in your browser with CachePDF.", summary: "Open local JPG images, set their order, and export a single new PDF.", steps: ["Open JPG images.", "Arrange the image order.", "Create the PDF locally.", "Export the PDF."], localBenefit: "Images are handled in the browser for this supported workflow, with no CachePDF document-processing upload.", related: ["/png-to-pdf", "/images-to-pdf", "/pdf-to-jpg"], acceptsImages: true, multi: true, faq: commonFaq("convert JPG images into PDF files in") },
  { path: "/png-to-pdf", toolSlug: "images-to-pdf", title: "PNG to PDF in Your Browser | CachePDF", h1: "Convert PNG images to PDF locally", description: "Create a PDF from PNG images directly in your browser with CachePDF.", summary: "Build a PDF from ordered local PNG images and export the resulting document.", steps: ["Open PNG images.", "Arrange the image order.", "Create the PDF locally.", "Export the PDF."], localBenefit: "The PDF is assembled locally and the source images remain in your browser session.", related: ["/jpg-to-pdf", "/images-to-pdf", "/pdf-to-png"], acceptsImages: true, multi: true, faq: commonFaq("convert PNG images into PDF files in") },
  { path: "/images-to-pdf", toolSlug: "images-to-pdf", title: "Images to PDF Locally | CachePDF", h1: "Convert images to PDF locally", description: "Build a PDF from local JPG or PNG images with CachePDF.", summary: "Use one browser-local image-to-PDF action for common image formats.", steps: ["Open local images.", "Check their order.", "Create a PDF locally.", "Export a new PDF."], localBenefit: "The supported image-to-PDF workflow processes the selected images inside the browser.", related: ["/jpg-to-pdf", "/png-to-pdf", "/pdf-to-jpg"], acceptsImages: true, multi: true, faq: commonFaq("convert images into PDF files in") },
  { path: "/pdf-to-jpg", toolSlug: "pdf-to-images", title: "PDF to JPG in Your Browser | CachePDF", h1: "Convert PDF pages to JPG locally", description: "Export selected PDF pages as JPEG images in a local ZIP archive.", summary: "Render selected PDF pages into JPEG files with scale and quality controls, then export one ZIP archive.", steps: ["Open a PDF.", "Select pages and choose JPEG.", "Choose quality and render scale.", "Export the image archive."], localBenefit: "Image rendering runs locally; larger documents receive browser-memory guidance before processing.", related: ["/pdf-to-png", "/pdf-to-webp", "/jpg-to-pdf"], faq: commonFaq("convert PDF pages to JPG in") },
  { path: "/pdf-to-png", toolSlug: "pdf-to-images", title: "PDF to PNG Locally | CachePDF", h1: "Convert PDF pages to PNG locally", description: "Export selected PDF pages as PNG images in your browser with CachePDF.", summary: "Choose selected pages and create a ZIP of lossless PNG page images locally.", steps: ["Open a PDF.", "Select pages and choose PNG.", "Choose a render scale.", "Export the ZIP archive."], localBenefit: "CachePDF renders page images through the browser and preserves the original PDF file.", related: ["/pdf-to-jpg", "/pdf-to-webp", "/png-to-pdf"], faq: commonFaq("convert PDF pages to PNG in") },
  { path: "/pdf-to-webp", toolSlug: "pdf-to-images", title: "PDF to WebP Locally | CachePDF", h1: "Convert PDF pages to WebP locally", description: "Export selected PDF pages as WebP images in a local ZIP archive.", summary: "Use WebP quality and render-scale controls to create a compact archive of selected local PDF pages.", steps: ["Open a PDF.", "Select pages and choose WebP.", "Set quality and scale.", "Export the ZIP archive."], localBenefit: "The browser performs the raster conversion for supported local workflows.", related: ["/pdf-to-jpg", "/pdf-to-png", "/images-to-pdf"], faq: commonFaq("convert PDF pages to WebP in") },
  { path: "/watermark-pdf", toolSlug: "add-watermark", title: "Watermark PDF Locally | CachePDF", h1: "Add a PDF watermark locally", description: "Add a text watermark to a new PDF directly in your browser.", summary: "Create a separate watermarked PDF without overwriting the original file.", steps: ["Open a PDF.", "Enter watermark text.", "Create the local output.", "Export the watermarked PDF."], localBenefit: "The watermark is drawn onto a new browser-generated output document.", related: ["/add-page-numbers-pdf", "/remove-pdf-metadata", "/merge-pdf"], faq: commonFaq("watermark") },
  { path: "/add-page-numbers-pdf", toolSlug: "add-page-numbers", title: "Add PDF Page Numbers Locally | CachePDF", h1: "Add PDF page numbers locally", description: "Create a numbered PDF in your browser with CachePDF.", summary: "Add lower-right page numbers to a fresh PDF output while the source document remains unchanged.", steps: ["Open a PDF.", "Review the numbering action.", "Create the local output.", "Export the numbered PDF."], localBenefit: "Numbering happens through the browser-side PDF library and creates a new output file.", related: ["/watermark-pdf", "/reorder-pdf-pages", "/merge-pdf"], faq: commonFaq("add page numbers to") },
  { path: "/ocr-pdf", toolSlug: "ocr-pdf", title: "OCR PDF in Your Browser | CachePDF", h1: "OCR PDF locally in your browser", description: "Recognize selected PDF pages in a browser worker and export text with CachePDF.", summary: "Render selected pages locally, recognize English text in a browser worker, then copy or export a TXT file.", steps: ["Open a PDF.", "Select pages for OCR.", "Run local OCR.", "Copy or export the text."], localBenefit: "OCR uses a browser worker. English language data can require network access before OCR can work offline; selected PDF contents are not sent to CachePDF for processing.", related: ["/private-pdf-tools", "/remove-pdf-metadata", "/pdf-to-png"], faq: commonFaq("OCR") },
  { path: "/view-pdf-metadata", toolSlug: "pdf-privacy-scanner", title: "View PDF Metadata Locally | CachePDF", h1: "View PDF metadata locally", description: "Inspect common PDF metadata fields in your browser with CachePDF.", summary: "Review common document metadata locally before sharing a PDF or generating a cleaned copy.", steps: ["Open a PDF.", "Run the local metadata scan.", "Review visible fields.", "Create a cleaned copy if needed."], localBenefit: "Metadata inspection reads common document fields in the browser for the selected local file.", related: ["/remove-pdf-metadata", "/private-pdf-tools", "/ocr-pdf"], faq: commonFaq("inspect PDF metadata in") },
  { path: "/remove-pdf-metadata", toolSlug: "remove-pdf-metadata", title: "Remove PDF Metadata Locally | CachePDF", h1: "Remove PDF metadata locally", description: "Create a new PDF without common metadata fields in your browser.", summary: "Remove common title, author, subject, keyword, creator, and producer metadata fields from a fresh output PDF.", steps: ["Open a PDF.", "Review the metadata action.", "Create the cleaned local output.", "Export the new PDF."], localBenefit: "The supported cleanup workflow creates a separate document output and does not modify the source file.", related: ["/view-pdf-metadata", "/private-pdf-tools", "/watermark-pdf"], faq: commonFaq("remove PDF metadata in") },
  { path: "/make-pdf-searchable", toolSlug: "make-pdf-searchable", title: "Make a PDF Searchable Locally | CachePDF", h1: "Make PDF searchable locally", description: "Add an invisible positioned OCR text layer to a new PDF in your browser with CachePDF.", summary: "Recognize selected scanned pages in a browser worker and create a new searchable PDF while preserving the visible page appearance.", steps: ["Open a scanned PDF.", "Choose pages to recognize.", "Create the searchable layer locally.", "Review and export the new PDF."], localBenefit: "OCR runs in a browser worker. Language data may require a download before first use, but selected PDF contents and recognized text are not sent to CachePDF for this supported workflow.", related: ["/ocr-pdf", "/pdf-to-png", "/document-privacy-check"], faq: commonFaq("make a PDF searchable in") },
  { path: "/sign-pdf", toolSlug: "sign-pdf", title: "Sign a PDF Locally | CachePDF", h1: "Sign PDF locally", description: "Place a typed, drawn, or image signature on a new PDF in your browser.", summary: "Choose a page, position a visual signature, and export a new PDF without overwriting the source document.", steps: ["Open a PDF.", "Choose a typed, drawn, or image signature.", "Place it on the selected page.", "Export the new PDF."], localBenefit: "Signature placement happens in the browser and creates a separate visual PDF output. It is not a certificate-backed or cryptographic digital signature.", related: ["/watermark-pdf", "/add-page-numbers-pdf", "/make-pdf-searchable"], faq: commonFaq("sign a PDF in") },
  { path: "/compress-pdf", toolSlug: "compress-pdf", title: "Compress a PDF Locally | CachePDF", h1: "Compress PDF locally", description: "Create a measured lower-footprint PDF in your browser and see the actual byte result before download.", summary: "Rebuild pages as JPEG-raster PDF output locally, compare the resulting byte size, and download only if the result fits your needs.", steps: ["Open a PDF.", "Choose a compression profile.", "Rebuild the PDF locally.", "Review the measured result and export if useful."], localBenefit: "CachePDF reports the actual output size and does not promise a reduction. This raster method can affect text, forms, links, layers, and image quality in the new output.", related: ["/pdf-to-jpg", "/make-pdf-searchable", "/document-privacy-check"], faq: commonFaq("compress a PDF in") },
  { path: "/document-privacy-check", toolSlug: "document-privacy-check", title: "Document Privacy Check Locally | CachePDF", h1: "Check a PDF for common document traces", description: "Review selected common PDF metadata, form, annotation, embedded-file, and document-action traces locally in your browser.", summary: "Inspect bounded common document traces, choose supported cleanup actions explicitly, and export a separate cleaned PDF for review.", steps: ["Open a PDF.", "Review the local findings.", "Select supported cleanup actions.", "Create and review a fresh PDF output."], localBenefit: "The check is browser-local and intentionally bounded. It is educational support, not a complete security audit or a guarantee that a document is safe to share.", related: ["/remove-pdf-metadata", "/private-pdf-tools", "/compress-pdf"], faq: commonFaq("run a document privacy check in") },
];

export const guideContent = [
  { slug: "merge-pdfs-without-uploading", title: "How to merge PDFs without uploading them", description: "A practical browser-local process for combining PDFs while keeping the source files under your control.", h1: "How to merge PDFs without uploading them", lead: "When a document set contains sensitive material, the key question is not only how to merge it, but where the transformation occurs.", tool: "/merge-pdf", steps: ["Open the local PDFs you need to combine.", "Set the order before creating the result.", "Merge locally and export the new document.", "Review the exported copy before sharing it." ] },
  { slug: "remove-pdf-metadata", title: "How to remove metadata from a PDF", description: "Understand common PDF metadata fields and create a cleaned browser-local output.", h1: "How to remove metadata from a PDF", lead: "PDF metadata can include common authorship and software fields that travel beyond the page content itself.", tool: "/remove-pdf-metadata", steps: ["Inspect common metadata fields locally.", "Decide whether a cleaned copy is appropriate.", "Create a new PDF without common metadata fields.", "Keep the original source file unchanged." ] },
  { slug: "ocr-scanned-pdf-locally", title: "How to OCR a scanned PDF locally", description: "Use browser-worker OCR to recognize selected PDF pages and export text.", h1: "How to OCR a scanned PDF locally", lead: "OCR can make scanned material more usable, but it is important to distinguish page processing from the language resource the recognizer may need.", tool: "/ocr-pdf", steps: ["Open the scanned PDF.", "Select pages that need recognition.", "Run OCR in the browser worker.", "Copy or export the result." ] },
  { slug: "rearrange-pdf-pages-privately", title: "How to rearrange PDF pages privately", description: "Use page thumbnails to review and reorder PDF pages in a browser-local workflow.", h1: "How to rearrange PDF pages privately", lead: "Reordering pages is easier to trust when the document sequence stays visible while the working copy remains local.", tool: "/reorder-pdf-pages", steps: ["Open the PDF.", "Review page thumbnails.", "Drag pages into the needed sequence.", "Export a new ordered copy." ] },
];

export const getLandingTool = (path: string) => landingTools.find((tool) => tool.path === path);
export const getGuide = (slug: string) => guideContent.find((guide) => guide.slug === slug);
