/**
 * OnePDF Design Note: About is intentionally direct and compact, presenting OnePDF as a focused
 * Nivaronix-adjacent product rather than inventing an oversized company narrative.
 */
import SiteShell from "@/components/SiteShell";
import { ArrowUpRight, FileLock2, Gauge, ShieldCheck } from "lucide-react";

export default function About() {
  return <SiteShell><main><section className="border-b border-white/[0.08] bg-[#090c11]"><div className="container grid gap-10 py-16 md:grid-cols-[1fr_0.8fr] md:items-end md:py-24"><div><div className="section-kicker">OnePDF by Nivaronix</div><h1 className="mt-5 max-w-3xl font-display text-5xl font-semibold leading-[0.93] tracking-[-0.07em] text-white sm:text-6xl">Document control should not begin with handing over a document.</h1></div><p className="max-w-lg text-lg leading-8 text-[#9ca9b9]">OnePDF is a browser-first PDF workbench built with the same practical trust mindset behind Nivaronix: make the operating boundary clear, keep the workflow focused, and let the evidence speak.</p></div></section><section className="container py-16 md:py-24"><div className="grid gap-5 md:grid-cols-3">{[{icon:ShieldCheck,title:"Privacy-minded",copy:"Local processing is preferred wherever browser technology can support it responsibly."},{icon:Gauge,title:"Focused utility",copy:"Each tool is designed around a specific document task, not a noisy all-purpose dashboard."},{icon:FileLock2,title:"Honest boundaries",copy:"Current capabilities and processing mode are visible before you start a document job."}].map((item)=><div className="surface p-7" key={item.title}><item.icon className="h-6 w-6 text-[#05c8f6]" strokeWidth={1.6}/><h2 className="mt-8 font-display text-2xl font-medium tracking-[-0.05em] text-white">{item.title}</h2><p className="mt-3 text-sm leading-7 text-[#98a4b5]">{item.copy}</p></div>)}</div></section><section className="border-y border-white/[0.08] bg-[#090c11]"><div className="container grid gap-8 py-16 md:grid-cols-[0.95fr_1.05fr] md:items-center md:py-20"><div><img src="/manus-storage/Nivaronix-Logo-light-extended_cb961f4e.svg" alt="Nivaronix" className="h-auto w-[230px]" /></div><div><div className="section-kicker">The parent brand</div><h2 className="mt-5 font-display text-4xl font-semibold leading-[0.98] tracking-[-0.06em] text-white">Built in the Nivaronix product tradition.</h2><p className="mt-5 max-w-xl leading-7 text-[#98a5b4]">OnePDF uses a pared-back version of the Nivaronix visual system: near-black surfaces, Signal Cyan for active state, and technically precise language for what the system is doing.</p><a href="https://nivaronix.com/" target="_blank" rel="noreferrer" className="button-secondary mt-7">Visit Nivaronix <ArrowUpRight className="h-4 w-4" /></a></div></div></section></main></SiteShell>;
}
