/**
 * CachePDF Design Note: The homepage treats the product workbench—not decorative art or a tool
 * directory—as the hero. Sparse, factual hierarchy makes the local-processing proposition clear.
 */
import SiteShell from "@/components/SiteShell";
import LocalSessionTrust from "@/components/LocalSessionTrust";
import { ToolGlyph } from "@/components/ToolGlyph";
import { ArrowRight, Check, FilePlus2 } from "lucide-react";
import { useDocumentSession } from "@/contexts/DocumentSessionContext";
import { cachepdfAssets } from "@/lib/cachepdfAssets";
import { trackCachePdfEvent } from "@/lib/telemetry";
import SEOHead from "@/components/SEOHead";
import { useTheme } from "@/contexts/ThemeContext";
import { Link, useLocation } from "wouter";
import { useRef, type ChangeEvent } from "react";

const modes = [
  { name: "Organize", slug: "merge-pdf", icon: "reorder", note: "Merge · reorder · split" },
  { name: "Convert", slug: "pdf-to-images", icon: "pdfimages", note: "PDF · PNG · JPEG · WebP" },
  { name: "Mark", slug: "add-watermark", icon: "watermark", note: "Watermark · page numbers" },
  { name: "Read", slug: "ocr-pdf", icon: "ocr", note: "OCR · text export" },
  { name: "Clean", slug: "pdf-privacy-scanner", icon: "metadata", note: "Inspect · remove metadata" },
];

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null);
  const { queueFiles } = useDocumentSession();
  const { theme } = useTheme();
  const [, setLocation] = useLocation();
  function openPdf(event: ChangeEvent<HTMLInputElement>) { const files = Array.from(event.target.files ?? []); event.target.value = ""; if (!files.length) return; trackCachePdfEvent("workbench_opened", { surface: "hero" }); queueFiles(files); setLocation("/tools/reorder-pages"); }
  const openLocal = () => { trackCachePdfEvent("open_pdf_clicked", { surface: "home" }); inputRef.current?.click(); };
  return <SiteShell><SEOHead title="CachePDF by Nivaronix — The Private PDF Workbench" description="Merge, split, organize, convert, OCR, and clean supported PDFs directly in your browser with CachePDF." path="/" schema={{ "@context": "https://schema.org", "@type": "SoftwareApplication", name: "CachePDF", applicationCategory: "UtilitiesApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } }} /><main>
    <section className="relative overflow-hidden border-b border-white/[0.08]"><input ref={inputRef} type="file" accept="application/pdf,.pdf" className="hidden" onChange={openPdf} /><div className="absolute inset-0 grid-fade" aria-hidden="true" /><div className="container relative grid min-h-[640px] gap-12 py-16 lg:grid-cols-[0.86fr_1.14fr] lg:items-center lg:py-20">
      <div className="max-w-xl"><img src={theme === "dark" ? cachepdfAssets.horizontalDark : cachepdfAssets.horizontalLight} alt="CachePDF by Nivaronix" className="h-10 w-auto max-w-[305px] object-contain object-left" /><div className="mt-4 section-kicker">Private PDF workbench</div><h1 className="mt-6 font-display text-[clamp(3.15rem,6.3vw,6.3rem)] font-semibold leading-[0.92] tracking-[-0.078em] text-white">The private <br /><span className="text-[#05c8f6]">PDF workbench.</span></h1><p className="mt-7 max-w-lg text-base leading-7 text-[#a7b0bf] sm:text-lg">Merge, split, organize, convert, OCR and clean PDFs directly in your browser.</p><p className="mt-4 font-medium text-[#e8eef5]">Your PDFs never leave your device.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button type="button" onClick={openLocal} className="button-primary justify-center tracking-[0.08em]">OPEN PDF <ArrowRight className="h-4 w-4" /></button><Link href="/how-cachepdf-works" className="button-secondary justify-center">How CachePDF works <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-10 flex flex-wrap gap-x-5 gap-y-3 border-t border-white/[0.09] pt-6">{["LOCAL PROCESSING", "NO FILE UPLOADS", "NO ACCOUNT REQUIRED", "ORIGINALS UNTOUCHED"].map((item) => <span key={item} className="inline-flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.13em] text-[#c8d2dc]"><Check className="h-3.5 w-3.5 text-[#05c8f6]" strokeWidth={2.5} />{item}</span>)}</div></div>
      <div className="surface relative overflow-hidden p-3 shadow-[0_28px_100px_rgba(0,0,0,0.42)] sm:p-5"><div className="relative rounded-[14px] border border-white/[0.1] bg-[#0a0e15]/96 p-4 sm:p-5"><div className="flex items-center justify-between border-b border-white/[0.08] pb-4"><div className="flex items-center gap-3"><img src={cachepdfAssets.appIconCyanAlt} alt="" className="h-8 w-8" /><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#e1e7ef]">CACHEPDF // WORKBENCH</p><p className="mt-1 text-xs text-[#8490a2]">Open. Work. Export. Nothing leaves.</p></div></div><LocalSessionTrust compact /></div><button type="button" onClick={openLocal} className="mt-5 flex min-h-[225px] w-full flex-col items-center justify-center rounded-[12px] border border-dashed border-[#05c8f6]/45 bg-[#05c8f6]/[0.04] px-5 text-center transition-colors hover:border-[#05c8f6] hover:bg-[#05c8f6]/[0.08]"><span className="flex h-12 w-12 items-center justify-center rounded-[11px] border border-[#05c8f6]/25 bg-[#0b1820] text-[#05c8f6]"><img src={cachepdfAssets.monogramCyan} alt="" className="h-6 w-6" /></span><span className="mt-4 font-display text-lg font-medium text-white">Open a PDF locally</span><span className="mt-1 text-sm text-[#8d99aa]">Choose a workflow. Your original stays unchanged.</span></button><div className="mt-4 grid grid-cols-3 gap-2.5"><div className="metric-chip"><span>Session</span><strong>Local</strong></div><div className="metric-chip"><span>Account</span><strong>None</strong></div><div className="metric-chip"><span>Original</span><strong>Untouched</strong></div></div></div></div>
    </div></section>
    <section className="container py-16 md:py-24"><div className="flex flex-col justify-between gap-5 border-b border-white/[0.08] pb-8 md:flex-row md:items-end"><div><div className="section-kicker">One workbench · five modes</div><h2 className="mt-4 max-w-2xl font-display text-4xl font-semibold leading-[0.98] tracking-[-0.06em] text-white md:text-5xl">Open once. Work locally. Export a fresh result.</h2></div><p className="max-w-sm text-sm leading-6 text-[#95a1b1]">The workbench groups PDF operations by intent, so the document workflow stays coherent from start to export.</p></div><div className="mt-7 grid gap-px overflow-hidden rounded-[16px] border border-white/[0.1] bg-white/[0.1] sm:grid-cols-2 lg:grid-cols-5">{modes.map((mode) => <Link href={`/tools/${mode.slug}`} className="tool-card group min-h-[166px] p-5" key={mode.name}><span className="flex h-9 w-9 items-center justify-center rounded-[9px] border border-white/[0.1] bg-[#0e131b] text-[#8fe7fb] group-hover:border-[#05c8f6]/45 group-hover:bg-[#05c8f6]/10"><ToolGlyph name={mode.icon} className="h-[18px] w-[18px]" /></span><h3 className="mt-6 font-display text-xl font-medium tracking-[-0.045em] text-white">{mode.name}</h3><p className="mt-2 text-xs leading-5 text-[#8d99aa]">{mode.note}</p><span className="mt-5 inline-flex items-center gap-1.5 font-mono text-[9px] uppercase tracking-[0.14em] text-[#05c8f6]">Open mode <ArrowRight className="h-3.5 w-3.5" /></span></Link>)}</div></section>
    <section className="border-y border-white/[0.08] bg-[#090c11]"><div className="container grid gap-10 py-16 md:grid-cols-[0.95fr_1.05fr] md:items-center md:py-20"><div><div className="section-kicker">Observable trust</div><h2 className="mt-5 font-display text-4xl font-semibold leading-[0.98] tracking-[-0.06em] text-white">Local processing is a visible state, not a vague promise.</h2><p className="mt-5 max-w-xl leading-7 text-[#98a5b4]">CachePDF opens supported documents in the browser, runs the transformation locally, and generates a new output for export. The source file remains unchanged.</p><Link href="/how-cachepdf-works" className="button-secondary mt-7">How CachePDF works <ArrowRight className="h-4 w-4" /></Link></div><div className="surface p-5 sm:p-7"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#69dff8]">● LOCAL SESSION</p><div className="mt-6 divide-y divide-white/[0.08] border-y border-white/[0.08]">{[["Document upload", "None"], ["Server processing", "None"], ["Account", "Not required"], ["Original", "Unchanged"]].map(([label, value]) => <div key={label} className="flex items-center justify-between gap-6 py-4"><span className="text-sm text-[#a6b1c0]">{label}</span><strong className="font-mono text-[10px] uppercase tracking-[0.12em] text-[#84e5f8]">{value}</strong></div>)}</div><div className="mt-5 flex gap-3 rounded-[10px] border border-[#05c8f6]/20 bg-[#05c8f6]/[0.05] p-4 text-sm leading-6 text-[#9ed7e6]">OCR language data may load when OCR is used. Document contents are not sent to CachePDF for supported local workflows.</div></div></div></section>
    <section className="border-t border-white/[0.08] bg-[#090c11]"><div className="container grid gap-8 py-12 md:grid-cols-[0.95fr_1.05fr] md:items-center md:py-16"><div><div className="section-kicker">Independent by design</div><h2 className="mt-4 font-display text-3xl font-semibold tracking-[-0.06em] text-white md:text-4xl">Keep CachePDF independent.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-[#99a5b5]">CachePDF stays free and accountless for supported browser-local work. Optional support helps maintain the product; public sponsorship inquiries never enter the document workbench.</p></div><div className="flex flex-wrap items-center gap-3 md:justify-end"><Link href="/support" className="button-secondary">Support CachePDF <ArrowRight className="h-4 w-4" /></Link><Link href="/advertise" className="button-secondary">Advertise with us <ArrowRight className="h-4 w-4" /></Link></div></div></section>
    <section className="container py-16 md:py-24"><div className="relative overflow-hidden rounded-[18px] border border-[#05c8f6]/24 bg-[#0b1119] px-7 py-12 sm:px-10 md:px-14 md:py-16"><div className="relative max-w-2xl"><div className="section-kicker">Ready to work</div><h2 className="mt-5 font-display text-4xl font-semibold leading-[0.98] tracking-[-0.06em] text-white md:text-5xl">Open a document. Keep the boundary clear.</h2><p className="mt-5 max-w-xl text-base leading-7 text-[#9eabbc]">No account is required for the supported browser-local workflows available today.</p><Link href="/tools" className="button-primary mt-8 tracking-[0.08em]">OPEN PDF <ArrowRight className="h-4 w-4" /></Link></div></div></section>
  </main></SiteShell>;
}
