/**
 * OnePDF Design Note: Pricing follows the parent brand’s transparent, no-clutter tone. It uses
 * a factual free-core offering and avoids invented product tiers or unverified feature claims.
 */
import SiteShell from "@/components/SiteShell";
import { ArrowRight, Check } from "lucide-react";
import { Link } from "wouter";

export default function Pricing() {
  const bullets = ["No account for local core tools", "Browser-first merge and organize workflows", "Image-to-PDF conversion", "Metadata scan and cleanup", "Fresh PDF download for every completed job"];
  return <SiteShell><main><section className="border-b border-white/[0.08] bg-[#090c11]"><div className="container py-16 text-center md:py-24"><div className="section-kicker justify-center">Transparent access</div><h1 className="mx-auto mt-5 max-w-3xl font-display text-5xl font-semibold leading-[0.93] tracking-[-0.07em] text-white sm:text-6xl">Start with the tools you need.</h1><p className="mx-auto mt-6 max-w-xl text-lg leading-8 text-[#9da9ba]">The browser-first core is free to use. OnePDF is structured so that advanced capabilities can be added with equally clear processing disclosure.</p></div></section><section className="container py-16 md:py-24"><div className="mx-auto grid max-w-5xl gap-6 md:grid-cols-[1.05fr_0.95fr]"><div className="relative overflow-hidden rounded-[18px] border border-[#05c8f6]/35 bg-[#0b141d] p-7 sm:p-9"><div className="absolute right-0 top-0 h-40 w-40 rounded-full bg-[#05c8f6]/15 blur-3xl" /><div className="relative"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#70dff8]">Available today</p><h2 className="mt-5 font-display text-3xl font-semibold tracking-[-0.055em] text-white">Free core tools</h2><p className="mt-2 text-sm leading-6 text-[#9aa6b7]">Local document operations with no account required.</p><p className="mt-7 font-display text-5xl font-semibold tracking-[-0.06em] text-white">$0<span className="ml-2 text-base font-normal tracking-normal text-[#92a0b2]">to begin</span></p><ul className="mt-8 space-y-4">{bullets.map((bullet)=><li key={bullet} className="flex gap-3 text-sm text-[#dce5ee]"><span className="mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-[#05c8f6]/15 text-[#05c8f6]"><Check className="h-3 w-3" strokeWidth={2.5}/></span>{bullet}</li>)}</ul><Link href="/tools" className="button-primary mt-9">Open the workbench <ArrowRight className="h-4 w-4" /></Link></div></div><div className="surface-quiet p-7 sm:p-9"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8491a4]">Future capabilities</p><h2 className="mt-5 font-display text-3xl font-semibold tracking-[-0.055em] text-white">Advanced processing</h2><p className="mt-3 text-sm leading-7 text-[#99a5b5]">Some document operations need more computational power or specialized processing than this lightweight browser build includes.</p><div className="mt-8 border-y border-white/[0.09] py-5"><p className="text-sm font-medium text-[#dfe7ef]">Potential extensions</p><p className="mt-2 text-sm leading-6 text-[#8490a2]">OCR, advanced redaction, high-fidelity conversion, sign workflows, and team-oriented document controls.</p></div><p className="mt-7 text-sm leading-6 text-[#9ba7b6]">When an advanced capability is introduced, its pricing and its processing boundary will be made explicit before the tool is used.</p><Link href="/privacy" className="button-ghost mt-7 px-0 text-[#78e0f8]">Read processing disclosure <ArrowRight className="h-4 w-4" /></Link></div></div></section></main></SiteShell>;
}
