import SiteShell from "@/components/SiteShell";
import { getCachePdfProProduct, getCachePdfProStatus, isAndroidStoreBuild, purchaseCachePdfPro, restoreCachePdfPro } from "@/lib/cachePdfPro";
import { ArrowRight, Check, LoaderCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

export default function Pricing() {
  const android = isAndroidStoreBuild(); const [entitled, setEntitled] = useState(false); const [price, setPrice] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!android) return; void Promise.all([getCachePdfProStatus(), getCachePdfProProduct()]).then(([status, product]) => { setEntitled(status.entitled); setPrice(product.price); }).catch(() => undefined); }, [android]);
  async function buy() { setBusy(true); try { const result = await purchaseCachePdfPro(); setEntitled(result.entitled); toast.success(result.state === "purchased" ? "CachePDF Pro is now active." : result.state === "pending" ? "Your Google Play purchase is pending." : "Purchase cancelled."); } catch { toast.error("Google Play could not complete this purchase."); } finally { setBusy(false); } }
  async function restore() { setBusy(true); try { const result = await restoreCachePdfPro(); setEntitled(result.entitled); toast.success(result.entitled ? "CachePDF Pro restored." : "No CachePDF Pro purchase was found for this Google Play account."); } catch { toast.error("Purchases could not be restored right now."); } finally { setBusy(false); } }
  return <SiteShell><main><section className="border-b border-white/[0.08] bg-[#090c11]"><div className="container py-16 text-center md:py-24"><div className="section-kicker justify-center">{android ? "Android purchase" : "Available now"}</div><h1 className="mx-auto mt-5 max-w-3xl font-display text-5xl font-semibold leading-[0.93] tracking-[-0.07em] text-white sm:text-6xl">{android ? "Advanced local workflows. Pay once." : "The local workbench is open."}</h1><p className="mx-auto mt-6 max-w-xl text-lg leading-8 text-[#9da9ba]">{android ? "CachePDF Pro is a one-time Google Play purchase. No CachePDF account and no document cloud are required." : "CachePDF’s supported browser-local workflows require no account."}</p></div></section><section className="container grid gap-6 py-16 md:grid-cols-2 md:py-24"><div className="rounded-[18px] border border-[#05c8f6]/35 bg-[#0b141d] p-7 sm:p-10"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#70dff8]">CachePDF Free</p><h2 className="mt-5 font-display text-3xl font-semibold tracking-[-0.055em] text-white">PDF essentials stay free</h2><p className="mt-3 text-sm leading-6 text-[#9aa6b7]">Organize, convert, mark, read, clean, and export supported PDF workflows locally.</p><ul className="mt-8 space-y-4">{["No account or subscription", "Original-safe local outputs", "Core PDF tools and basic OCR"].map((bullet) => <li key={bullet} className="flex gap-3 text-sm text-[#dce5ee]"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#05c8f6]" />{bullet}</li>)}</ul><Link href="/tools" className="button-primary mt-9 tracking-[0.08em]">OPEN PDF <ArrowRight className="h-4 w-4" /></Link></div>{android && <div className="rounded-[18px] border border-amber-300/35 bg-amber-300/[.06] p-7 sm:p-10"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-amber-200">CachePDF Pro</p><h2 className="mt-5 font-display text-3xl font-semibold tracking-[-0.055em] text-white">{entitled ? "Pro is active" : price || "One-time purchase"}</h2><p className="mt-3 text-sm leading-6 text-[#f4e2bc]">Unlock advanced local productivity: searchable OCR PDFs, advanced compression, batch workflows, advanced privacy actions, and workflow presets as they are completed.</p><p className="mt-5 font-mono text-[10px] uppercase tracking-[.14em] text-amber-100/80">One-time purchase · no CachePDF account · documents stay on device</p>{entitled ? <Link href="/tools" className="button-primary mt-8">OPEN PRO WORKFLOWS <ArrowRight className="h-4 w-4" /></Link> : <div className="mt-8 flex flex-wrap gap-3"><button type="button" className="button-primary" disabled={busy} onClick={() => void buy()}>{busy && <LoaderCircle className="h-4 w-4 animate-spin" />} UNLOCK PRO</button><button type="button" className="button-secondary" disabled={busy} onClick={() => void restore()}>RESTORE PURCHASE</button></div>}</div>}</section></main></SiteShell>;
}
