/**
 * OnePDF Design Note: Privacy content uses restrained evidence modules and a document boundary
 * metaphor, translating Nivaronix security language into clear, honest product disclosure.
 */
import SiteShell from "@/components/SiteShell";
import { ArrowRight, CheckCircle2, CircleAlert, Laptop, Server, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export default function Privacy() {
  return <SiteShell><main>
    <section className="relative overflow-hidden border-b border-white/[0.08] bg-[#090c11]"><div className="container grid gap-10 py-16 md:grid-cols-[1fr_0.86fr] md:items-center md:py-24"><div><div className="section-kicker"><span className="status-dot" /> Processing disclosure</div><h1 className="mt-6 font-display text-5xl font-semibold leading-[0.92] tracking-[-0.07em] text-white sm:text-6xl">A clear boundary for every file.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#a4afbf]">OnePDF is designed to keep common PDF jobs inside the browser. When a workflow needs a different processing model, the product should say so before you begin.</p><Link href="/tools/pdf-privacy-scanner" className="button-primary mt-8">Inspect a PDF locally <ArrowRight className="h-4 w-4" /></Link></div><div className="relative mx-auto w-full max-w-[420px]"><div className="absolute -inset-12 rounded-full bg-[#05c8f6]/10 blur-[80px]" /><div className="relative overflow-hidden rounded-[18px] border border-white/[0.12] bg-[#0b1018] p-4"><img src="/manus-storage/onepdf-privacy-surface_0b6e06ed.png" alt="Documents within a protected local processing boundary" className="aspect-square w-full rounded-[12px] object-cover" /><div className="mt-4 flex items-center gap-3 border-t border-white/[0.08] pt-4"><span className="flex h-8 w-8 items-center justify-center rounded-[8px] bg-[#05c8f6]/10 text-[#05c8f6]"><Laptop className="h-4 w-4" /></span><div><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-[#dfe8f0]">Supported workflow</p><p className="mt-0.5 text-xs text-[#8794a6]">This device processes the document</p></div></div></div></div></div></section>
    <section className="container py-16 md:py-24"><div className="max-w-2xl"><div className="section-kicker">How it works</div><h2 className="mt-5 font-display text-4xl font-semibold leading-[0.98] tracking-[-0.06em] text-white md:text-5xl">Local when practical. Explicit when not.</h2></div><div className="mt-12 grid gap-px overflow-hidden rounded-[18px] border border-white/[0.1] bg-white/[0.1] md:grid-cols-3">{[{ n:"01", icon:Laptop, title:"Choose a tool", text:"Open the focused workspace for the document operation you need." },{ n:"02", icon:ShieldCheck, title:"Check the mode", text:"The tool labels whether the browser can process this operation locally." },{ n:"03", icon:CheckCircle2, title:"Receive a fresh copy", text:"Download the new result while the source document stays untouched." }].map((item)=><div className="bg-[#090d13] p-7" key={item.n}><span className="font-mono text-[10px] tracking-[0.16em] text-[#05c8f6]">{item.n}</span><item.icon className="mt-10 h-7 w-7 text-[#8fe7fb]" strokeWidth={1.5}/><h3 className="mt-5 font-display text-xl font-medium tracking-[-0.04em] text-white">{item.title}</h3><p className="mt-3 text-sm leading-6 text-[#8d99aa]">{item.text}</p></div>)}</div></section>
    <section className="border-y border-white/[0.08] bg-[#090c11]"><div className="container grid gap-8 py-16 md:grid-cols-2 md:py-20"><div className="surface p-7"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-[9px] bg-[#05c8f6]/10 text-[#05c8f6]"><Laptop className="h-5 w-5" /></span><div><p className="font-display text-xl font-medium tracking-[-0.04em] text-white">Local processing</p><p className="mt-1 text-sm text-[#8d99aa]">Available in the browser today</p></div></div><ul className="mt-7 space-y-4">{["Merge multiple PDFs", "Split, extract, reorder, delete, or rotate pages", "Create PDFs from JPG and PNG images", "Add page numbers or a text watermark", "Inspect and remove common PDF metadata"].map((point)=><li key={point} className="flex gap-3 text-sm leading-6 text-[#c5cfda]"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#05c8f6]" />{point}</li>)}</ul></div><div className="surface-quiet p-7"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-[9px] bg-[#f47575]/10 text-[#fda4a4]"><Server className="h-5 w-5" /></span><div><p className="font-display text-xl font-medium tracking-[-0.04em] text-white">Beyond the current browser engine</p><p className="mt-1 text-sm text-[#8d99aa]">Clearly marked before use</p></div></div><p className="mt-7 text-sm leading-7 text-[#a0acbc]">Capabilities such as high-fidelity OCR, permanent visual redaction, or advanced conversion may require additional browser modules or a future secure processing service. OnePDF should not present them as local until that is true.</p><div className="mt-6 flex gap-3 rounded-[10px] border border-[#f47575]/20 bg-[#f47575]/[0.06] p-3 text-xs leading-5 text-[#cfafb5]"><CircleAlert className="h-4 w-4 shrink-0 text-[#fda4a4]" />A processing boundary is a product promise. This interface makes it visible before a file is selected.</div></div></div></section>
    <section className="container py-16 md:py-24"><div className="max-w-3xl rounded-[18px] border border-white/[0.1] bg-[#0a0e14] p-7 sm:p-10"><div className="section-kicker">What OnePDF does not do</div><h2 className="mt-5 font-display text-3xl font-semibold tracking-[-0.06em] text-white">It does not modify the original you select.</h2><p className="mt-5 max-w-2xl leading-7 text-[#99a5b5]">Document operations create new output files. You remain responsible for choosing an appropriate workflow and for securely handling any downloaded result on your device.</p><Link href="/tools" className="button-secondary mt-7">Browse local tools <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main></SiteShell>;
}
