/**
 * CachePDF Design Note: How CachePDF Works explains the browser-local architecture with concise,
 * verifiable statements. It avoids absolute claims about unrelated network activity.
 */
import SEOHead from "@/components/SEOHead";
import SiteShell from "@/components/SiteShell";
import { cachepdfAssets } from "@/lib/cachepdfAssets";
import { ArrowRight, CheckCircle2, Code2, Download, FilePlus2, Laptop, ScanText } from "lucide-react";
import { Link } from "wouter";

const steps = [
  { code: "01", icon: FilePlus2, title: "Open", text: "Your browser opens the selected document for a supported local workflow." },
  { code: "02", icon: Code2, title: "Work", text: "PDF libraries and browser workers transform the working copy on this device." },
  { code: "03", icon: Download, title: "Export", text: "CachePDF generates a fresh PDF, image archive, text file, or ZIP for you to export." },
  { code: "04", icon: CheckCircle2, title: "Nothing leaves", text: "Document contents are not sent to CachePDF for supported local-processing workflows." },
];

export default function Privacy() {
  return <SiteShell>
    <SEOHead title="How CachePDF Works | Browser-Local PDF Processing" description="Learn how CachePDF processes supported PDF workflows locally in the browser and keeps source files unchanged." path="/how-cachepdf-works" schema={{ "@context": "https://schema.org", "@type": "WebPage", name: "How CachePDF Works", description: "Browser-local PDF workflow information from CachePDF by Nivaronix." }} />
    <main>
      <section className="border-b border-white/[0.08] bg-[#090c11]"><div className="container grid gap-10 py-16 md:grid-cols-[1fr_0.8fr] md:items-center md:py-24"><div><img src={cachepdfAssets.wordmarkDark} alt="CachePDF" className="h-6 w-auto invert" /><div className="section-kicker mt-5">How CachePDF works</div><h1 className="mt-6 font-display text-5xl font-semibold leading-[0.92] tracking-[-0.07em] text-white sm:text-6xl">Open. Work. Export. Nothing leaves.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#a4afbf]">CachePDF is a browser-local PDF workbench. Supported document operations happen on your device instead of sending your document to a processing server.</p><Link href="/tools" className="button-primary mt-8 tracking-[0.08em]">OPEN PDF <ArrowRight className="h-4 w-4" /></Link></div><div className="surface p-6 sm:p-7"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#70dff8]">● LOCAL SESSION</p><div className="mt-5 divide-y divide-white/[0.08] border-y border-white/[0.08]">{[["Document upload", "None"], ["Server-side processing", "None"], ["Account required", "No"], ["Original modified", "No"]].map(([label, value]) => <div key={label} className="flex items-center justify-between gap-5 py-4"><span className="text-sm text-[#9aa7b7]">{label}</span><strong className="font-mono text-[10px] uppercase tracking-[0.12em] text-[#83e2f6]">{value}</strong></div>)}</div></div></div></section>
      <section className="container py-16 md:py-24"><div className="grid gap-px overflow-hidden rounded-[18px] border border-white/[0.1] bg-white/[0.1] md:grid-cols-2">{steps.map((step) => <div className="bg-[#090d13] p-7" key={step.code}><span className="font-mono text-[10px] tracking-[0.16em] text-[#05c8f6]">{step.code}</span><step.icon className="mt-10 h-7 w-7 text-[#8fe7fb]" strokeWidth={1.5} /><h2 className="mt-5 font-display text-2xl font-medium tracking-[-0.05em] text-white">{step.title}</h2><p className="mt-3 text-sm leading-7 text-[#8d99aa]">{step.text}</p></div>)}</div></section>
      <section className="border-y border-white/[0.08] bg-[#090c11]"><div className="container grid gap-8 py-16 md:grid-cols-2 md:py-20"><div className="surface p-7"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-[9px] bg-[#05c8f6]/10 text-[#05c8f6]"><Laptop className="h-5 w-5" /></span><div><p className="font-display text-xl font-medium tracking-[-0.04em] text-white">What runs locally</p><p className="mt-1 text-sm text-[#8d99aa]">Available in the current browser build</p></div></div><p className="mt-6 text-sm leading-7 text-[#a5b0bf]">PDF manipulation uses browser-side libraries for merge, page organization, metadata cleanup, watermarks, page numbering, image conversion, and individual-page split exports.</p></div><div className="surface-quiet p-7"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-[9px] bg-[#05c8f6]/10 text-[#05c8f6]"><ScanText className="h-5 w-5" /></span><div><p className="font-display text-xl font-medium tracking-[-0.04em] text-white">OCR transparency</p><p className="mt-1 text-sm text-[#8d99aa]">Language data may load before recognition</p></div></div><p className="mt-6 text-sm leading-7 text-[#a5b0bf]">OCR renders selected pages locally and recognizes text in a browser worker. The OCR language model can require a download on first use; the selected PDF contents are not uploaded to CachePDF.</p></div></div></section>
      <section className="container py-16 md:py-24"><div className="max-w-3xl rounded-[18px] border border-white/[0.1] bg-[#0a0e14] p-7 sm:p-10"><div className="section-kicker">Original-safe by design</div><h2 className="mt-5 font-display text-3xl font-semibold tracking-[-0.06em] text-white">Open the original. Export the result.</h2><p className="mt-5 max-w-2xl leading-7 text-[#99a5b5]">CachePDF creates new output files from a working state. It does not destructively modify the source file you choose.</p><Link href="/tools" className="button-secondary mt-7">Open the workbench <ArrowRight className="h-4 w-4" /></Link></div></section>
    </main>
  </SiteShell>;
}
