/** CachePDF Design Note: Search landings are compact product pathways, not disconnected SEO shells.
 * They lead directly to an available local action and state the browser-processing boundary plainly. */
import SEOHead from "@/components/SEOHead";
import SiteShell from "@/components/SiteShell";
import { getLandingTool, landingTools } from "@/lib/seoContent";
import { canonicalUrl } from "@/lib/site";
import { ArrowRight, Check, ShieldCheck } from "lucide-react";
import { Link, useLocation } from "wouter";

export default function ToolLanding() {
  const [location] = useLocation();
  const tool = getLandingTool(location);
  if (!tool) return null;
  const schema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "CachePDF", applicationCategory: "UtilitiesApplication", operatingSystem: "Web", description: tool.description, url: canonicalUrl(tool.path), offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } };
  return <SiteShell><SEOHead title={tool.title} description={tool.description} path={tool.path} schema={schema} /><main>
    <section className="border-b border-white/[0.08] bg-[#090c11]"><div className="container grid gap-10 py-16 md:grid-cols-[1.05fr_.75fr] md:items-end md:py-24"><div><div className="section-kicker">CachePDF local tool</div><h1 className="mt-5 max-w-3xl font-display text-5xl font-semibold leading-[.93] tracking-[-.07em] text-white sm:text-6xl">{tool.h1}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#a0adbd]">{tool.summary}</p><Link href={`/tools/${tool.toolSlug}`} className="button-primary mt-8 tracking-[.08em]">OPEN TOOL <ArrowRight className="h-4 w-4" /></Link></div><div className="surface p-6"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#70dff8]">● LOCAL PROCESSING</p><p className="mt-5 text-sm leading-7 text-[#a5b0bf]">{tool.localBenefit}</p><div className="mt-6 space-y-3 border-t border-white/[.08] pt-5">{["No account required", "Original file unchanged", "New output on export"].map((item) => <p key={item} className="flex items-center gap-2 text-sm text-[#dce5ee]"><Check className="h-4 w-4 text-[#05c8f6]" />{item}</p>)}</div></div></div></section>
    <section className="container py-16 md:py-24"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><div className="section-kicker">How it works</div><h2 className="mt-5 font-display text-4xl font-semibold tracking-[-.06em] text-white">A direct local workflow.</h2><p className="mt-5 leading-7 text-[#98a5b4]">CachePDF opens the selected document in the browser, applies the available tool action locally, and prepares a separate output for export.</p></div><ol className="grid gap-px overflow-hidden rounded-[16px] border border-white/[.1] bg-white/[.1] sm:grid-cols-2">{tool.steps.map((step, index) => <li key={step} className="bg-[#090d13] p-6"><span className="font-mono text-[10px] tracking-[.16em] text-[#05c8f6]">0{index + 1}</span><p className="mt-6 font-display text-xl font-medium tracking-[-.04em] text-white">{step}</p></li>)}</ol></div></section>
    <section className="border-y border-white/[.08] bg-[#090c11]"><div className="container grid gap-10 py-16 md:grid-cols-[.85fr_1.15fr] md:py-20"><div><div className="section-kicker">Privacy by design</div><h2 className="mt-5 font-display text-3xl font-semibold tracking-[-.055em] text-white">The processing boundary stays visible.</h2><Link href="/how-cachepdf-works" className="button-secondary mt-7">How CachePDF works <ArrowRight className="h-4 w-4" /></Link></div><div className="rounded-[14px] border border-[#05c8f6]/20 bg-[#05c8f6]/[.05] p-6"><ShieldCheck className="h-6 w-6 text-[#05c8f6]" /><p className="mt-5 text-base leading-7 text-[#a9ddea]">Supported document operations run in the browser. CachePDF does not require a CachePDF account or server-side document-processing upload for these local workflows.</p></div></div></section>
    <section className="container py-16 md:py-24"><div className="flex flex-col justify-between gap-5 border-b border-white/[.08] pb-7 md:flex-row md:items-end"><div><div className="section-kicker">Related local tools</div><h2 className="mt-4 font-display text-3xl font-semibold tracking-[-.055em] text-white">Continue in the workbench.</h2></div><Link href="/tools" className="text-sm text-[#70dff8]">View all tools →</Link></div><div className="mt-7 grid gap-3 sm:grid-cols-3">{tool.related.map((relatedPath) => { const related = getLandingTool(relatedPath); return related ? <Link key={related.path} href={related.path} className="surface-quiet p-5 transition-colors hover:border-[#05c8f6]/40"><p className="font-display text-lg font-medium tracking-[-.04em] text-white">{related.h1}</p><p className="mt-2 text-sm leading-6 text-[#8e9bab]">{related.description}</p></Link> : null; })}</div></section>
    <section className="border-t border-white/[.08]"><div className="container max-w-4xl py-16 md:py-20"><div className="section-kicker">Questions</div><h2 className="mt-4 font-display text-3xl font-semibold tracking-[-.055em] text-white">Tool FAQ</h2><div className="mt-8 divide-y divide-white/[.08] border-y border-white/[.08]">{tool.faq.map((item) => <div key={item.question} className="py-6"><h3 className="font-display text-lg font-medium text-white">{item.question}</h3><p className="mt-2 leading-7 text-[#99a5b5]">{item.answer}</p></div>)}</div></div></section>
  </main></SiteShell>;
}

export const landingPaths = landingTools.map((tool) => tool.path);
